### ISSUE TITLE
Endless buffering on lock/unlock phone

### ISSUE THREAD

**Issue by twerq** [yagiz/andromeda#2]
On Samsung A5 ( SM-A500f ) built-in browser. Application goes quite good ( with small gfx glitches though ). Then off the screen (lock phone), then unlock and switch back to browser.
Andromeda gets in endless buffering. Shows animation, but no any noise. And Buffering… message on the screen

What expected: some buffering and continue the show.

**Comment by yagiz** [comment]
I tested the scenario on iPhone 6S iOS 10.3 and it has the same issue. I'll inspect it.

**Comment by yagiz** [comment]
I think I solved the issue. I tested on my  iPhone 6S iOS 10.3. After unlock, YouTube player and animations keep playing. Would you also test it on Android? @infodiver 

https://github.com/yagiz/Andromeda/commit/1d8cb449b017de169bce78eb94eda7a9caa978d0

**Comment by twerq** [comment]
Now app goes as expected.
Thank you!
